### ISSUE TITLE
Update nullable columns to NULL is not reported correctly

### ISSUE THREAD

**Issue by Oli180369** [thake/logminer-kafka-connect#14]
If a nullable column is updated with NULL the new value is not reported as NULL, much more the old value is reported as the new value.

**Comment by thake** [comment]
Can you provide a PR with a reproducable failing unit test?

As a starting point you can have a look at the existing unit tests.

Oli180369 <notifications@github.com> schrieb am Do., 4. März 2021, 09:02:

**Comment by Oli180369** [comment]
Seems that we have an issue with the logminer itself

**Comment by Oli180369** [comment]
We checked the tables on which the logminer-kafka-connect component is working. These tables were filled correctly. There has to be an issue with the component. We try to improve the test

**Comment by Oli180369** [comment]
It seems that we have a problem within the ConnectSchemaFactrory at line 99 where the after struct is enriched by before values for absent keys. At this point the component can not distinguish an absence from an NULL-Update because the Hashmap will return NULL in both cases. So the after struct is always enriched by the before struct for columns which are updated to NULL.
I was not able to provide a test for this issue so far, but I hope you have understood.

**Comment by thake** [comment]
@Oli180369 Thanks for this patch! A tricky bug.. ;)

I'll prepare a new release just now.
