### ISSUE TITLE
About Oracle 10g

### ISSUE THREAD

**Issue by J-Junfan** [thake/logminer-kafka-connect#3]
Hello！
    Our company currently receives the Oracle 10g used by the project.I read the documentation, You passed the 11g test and may support 19c. But there is no mention of Oracle 10g.Can I use this project when the Oracle version is 10g？

**Comment by thake** [comment]
It should be possible without problems. But it is not tested.

J-Junfan <notifications@github.com> schrieb am Mi., 1. Juli 2020, 04:09:

**Comment by J-Junfan** [comment]
Thank you for your answer.If successful, I will give you feedback.Thank you！

**Comment by thake** [comment]
@J-Junfan Did you have any success?

**Comment by thake** [comment]
@J-Junfan I will close this issue if I do not hear from you. I don't have the possibility to verify the compatibility to Oracle 10g.

**Comment by J-Junfan** [comment]
Thank you very much for receiving your letter！Later my supervisor chose another project. At that time, I looked at the code of your project, and some Oracle attributes have different values. Supporting Oracle 10g may be too much work.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thake/logminer-kafka-connect"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月27日(星期二) 下午3:42
收件人:&nbsp;"thake/logminer-kafka-connect"<logminer-kafka-connect@noreply.github.com&gt;;
抄送:&nbsp;"金峻帆（Jin Junfan）"<1367547670@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [thake/logminer-kafka-connect] About Oracle 10g (#3)





 
@J-Junfan I will close this issue if I do not hear from you. I don't have the possibility to verify the compatibility to Oracle 10g.

**Comment by thake** [comment]
@J-Junfan thanks for your feedback. Closing this issue as wontfix.
